version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    volumes:
      - ./instance:/app/instance

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: farmtasks_user
      POSTGRES_PASSWORD: farmtasks_password
      POSTGRES_DB: farmtasks_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U farmtasks_user -d farmtasks_data"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: farmtasks_postgres_data
