version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: farmtasks_user
      POSTGRES_PASSWORD: farmtasks_password
      POSTGRES_DB: farmtasks_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U farmtasks_user -d farmtasks_data"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: farmtasks_postgres_data